openapi: 3.0.3
info:
  contact:
    email: info@affinidi.com
    name: Affinidi
    url: https://github.com/affinidi/affinidi-tdk
  license:
    name: Apache-2.0
    url: https://github.com/affinidi/affinidi-tdk/blob/main/LICENSE
  title: VerificationService
  version: 1.0.0
externalDocs:
  description: Affinidi Documentation Website
  url: https://docs.affinidi.com/dev-tools/affinidi-tdk/clients/credential-verification
servers:
  - url: https://apse1.api.affinidi.io/ver
security:
  - AwsSigV4: []
tags:
  - description: Verifying operations
    name: verifier
  - description: path method published as part of Affinidi TDK
    name: x-affinidi-tdk
paths:
  /v1/verifier/verify-vcs:
    post:
      description: |-
        Verifying Verifiable Credentials (signatures)

        `isValid` - true if all credentials verified
        `errors` contains list of error messages for invalid credentials.
      operationId: verifyCredentials
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/VerifyCredentials'
      responses:
        '200':
          content:
            application/json:
              example:
                isValid: true
                errors: []
              schema:
                $ref: '#/components/schemas/VerifyCredentialOutput'
          description: Ok
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterError'
          description: BadRequestError
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: NotFoundError
      security:
        - ProjectTokenAuth: []
      summary: Verifying VC
      tags: []
      x-content-type: application/json
      x-accepts:
        - application/json
  /v1/verifier/verify-vp:
    post:
      description: |-
        Verifying Verifiable Presentation (signatures)

        `isValid` - true if presentation verified
        `error` verificaction error.
      operationId: verifyPresentation
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/VerifyPresentation'
      responses:
        '200':
          content:
            application/json:
              example:
                isValid: true
                error: ''
              schema:
                $ref: '#/components/schemas/VerifyPresentationOutput'
          description: Ok
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterError'
          description: BadRequestError
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: NotFoundError
      security:
        - ProjectTokenAuth: []
      summary: Verifying VP
      tags: []
      x-content-type: application/json
      x-accepts:
        - application/json
components:
  examples: {}
  headers: {}
  requestBodies:
    ValidateJwt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidateJwtInput'
      description: ValidateJwt
      required: true
    VerifyCredentials:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VerifyCredentialInput'
      description: VerifyCredentials
      required: true
    VerifyPresentation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VerifyPresentationInput'
      description: VerifyPresentation
      required: true
  responses:
    ValidateJwtOK:
      content:
        application/json:
          example:
            isValid: true
            payload:
              foo: bar
          schema:
            $ref: '#/components/schemas/ValidateJwtOutput'
      description: OK
    VerifyCredentialsOK:
      content:
        application/json:
          example:
            isValid: true
            errors: []
          schema:
            $ref: '#/components/schemas/VerifyCredentialOutput'
      description: Ok
    VerifyPresentationOK:
      content:
        application/json:
          example:
            isValid: true
            error: ''
          schema:
            $ref: '#/components/schemas/VerifyPresentationOutput'
      description: Ok
    ValidateJwtBadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidParameterError'
      description: BadRequestError
    ValidateJwtNotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
      description: NotFoundError
    VerifyCredentialsBadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidParameterError'
      description: BadRequestError
    VerifyCredentialsNotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
      description: NotFoundError
    VerifyPresentationBadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidParameterError'
      description: BadRequestError
    VerifyPresentationNotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
      description: NotFoundError
  schemas:
    ValidateJwtOutput:
      additionalProperties: false
      description: Response model of /validate-jwt
      properties:
        isValid:
          description: Defines if jwt is valid
          type: boolean
        payload:
          description: Decoded payload of the token
          type: object
      required:
        - isValid
        - payload
      type: object
    ValidateJwtInput:
      additionalProperties: false
      description: Request model of /validate-jwt
      properties:
        token:
          description: JWT token
          type: string
      required:
        - token
      type: object
    VerifyCredentialOutput:
      additionalProperties: false
      description: Response model of /verify-vcs
      example:
        isValid: true
        errors:
          - errors
          - errors
      properties:
        errors:
          description: Errors of the VCs failed verification
          items:
            type: string
          type: array
        isValid:
          description: Verification result
          type: boolean
      required:
        - errors
        - isValid
      type: object
    VerifyCredentialInput:
      additionalProperties: false
      description: Request model of /verify-vcs
      example:
        verifiableCredentials:
          - null
          - null
        issuerDidDocument:
          key: ''
      properties:
        verifiableCredentials:
          description: List of VCs
          items:
            $ref: '#/components/schemas/W3cCredential'
          minItems: 1
          type: array
        issuerDidDocument:
          additionalProperties: true
          description: Dynamic model
          type: object
      required:
        - verifiableCredentials
      type: object
    VerifyPresentationOutput:
      additionalProperties: false
      description: Response model of /verify-vp
      example:
        isValid: true
        errors:
          - errors
          - errors
      properties:
        errors:
          description: Error of the verification
          items:
            type: string
          type: array
        isValid:
          description: Verification result
          type: boolean
      required:
        - errors
        - isValid
      type: object
    VerifyPresentationInput:
      additionalProperties: false
      description: Request model of /verify-vp
      example:
        presentationDefinition: '{}'
        verifiablePresentation: '{}'
        signedPresentation: '{}'
        challenge: challenge
        presentationSubmission: '{}'
      properties:
        verifiablePresentation:
          type: object
        signedPresentation:
          type: object
        presentationDefinition:
          type: object
        presentationSubmission:
          type: object
        challenge:
          type: string
      type: object
    UrlType:
      description: Type of the URL
      pattern: ^https?:\/\/.*$
      type: string
    CredentialRequirements:
      additionalProperties: false
      description: Requirements of the VC
      properties:
        type:
          description: Type list of the VC requirements
          items:
            type: string
          type: array
        constraints:
          $ref: '#/components/schemas/CredentialRequirements_constraints'
      required:
        - type
      type: object
    DidType:
      description: Type of the DID
      pattern: did:.*
      type: string
    DateISOType:
      description: Type of the Date ISO
      pattern:
        "\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\\
        d:[0-5]\\d|Z)"
      type: string
    ErrorDetail:
      description: Detail of the error
      properties:
        message:
          description: Error detail message
          type: string
      type: object
    Error:
      description: Error object
      properties:
        errorCode:
          description: Error code
          type: string
        errorMessage:
          description: Error message
          type: string
        message:
          description: Verbose message
          type: string
        name:
          description: Error name
          type: string
        debugId:
          description: Debug identifier
          type: string
        details:
          description: Error details
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
      type: object
    EvaluateVpOutput:
      additionalProperties: false
      properties:
        result:
          type: boolean
        errors:
          items:
            type: string
          type: array
      required:
        - errors
        - result
      type: object
    W3cPresentation:
      type: object
    W3cCredential:
      type: object
    W3cProof:
      additionalProperties: false
      properties:
        type:
          nullable: true
          type: string
        created:
          nullable: true
          type: string
        verificationMethod:
          type: string
        proofPurpose:
          type: string
        jws:
          nullable: true
          type: string
        proofValue:
          nullable: true
          type: string
        nonce:
          nullable: true
          type: string
      required:
        - proofPurpose
        - verificationMethod
      type: object
    W3cCredentialStatus:
      additionalProperties: false
      properties:
        id:
          type: string
        type:
          type: string
        revocationListIndex:
          type: string
        revocationListCredential:
          type: string
      required:
        - id
        - revocationListCredential
        - revocationListIndex
        - type
      type: object
    PresentationDefinition:
      additionalProperties: false
      description: Presentation definition
      properties:
        id:
          description: Definition id
          type: string
        name:
          description: Definition name
          type: string
        purpose:
          description: Definition purpose
          type: string
        format:
          $ref: '#/components/schemas/Format'
        submission_requirements:
          items:
            $ref: '#/components/schemas/SubmissionRequirement'
          type: array
        input_descriptors:
          items:
            $ref: '#/components/schemas/InputDescriptor'
          type: array
        frame:
          additionalProperties: true
          description: Dynamic model
          type: object
      required:
        - id
        - input_descriptors
      type: object
    PresentationSubmission:
      additionalProperties: false
      properties:
        id:
          type: string
        definition_id:
          type: string
        descriptor_map:
          items:
            $ref: '#/components/schemas/Descriptor'
          type: array
      required:
        - definition_id
        - descriptor_map
        - id
      type: object
    Descriptor:
      additionalProperties: false
      properties:
        id:
          type: string
        path:
          type: string
        path_nested:
          $ref: '#/components/schemas/NestedDescriptor'
        format:
          type: string
      required:
        - format
        - id
        - path
      type: object
    NestedDescriptor:
      additionalProperties: false
      properties:
        id:
          type: string
        path:
          type: string
        path_nested:
          $ref: '#/components/schemas/NestedDescriptor'
        format:
          type: string
      required:
        - format
        - path
      type: object
    Format:
      additionalProperties: false
      properties:
        jwt:
          $ref: '#/components/schemas/JwtObject'
        jwt_vc:
          $ref: '#/components/schemas/JwtObject'
        jwt_vp:
          $ref: '#/components/schemas/JwtObject'
        ldp:
          $ref: '#/components/schemas/LdpObject'
        ldp_vc:
          $ref: '#/components/schemas/LdpObject'
        ldp_vp:
          $ref: '#/components/schemas/LdpObject'
      type: object
    JwtObject:
      additionalProperties: false
      properties:
        alg:
          description: List of names of the the JWT Algorithms
          items:
            type: string
          type: array
      required:
        - alg
      type: object
    LdpObject:
      additionalProperties: false
      properties:
        proof_type:
          description: List of names of the proof types
          items:
            type: string
          type: array
      required:
        - proof_type
      type: object
    SubmissionRequirement:
      additionalProperties: false
      properties:
        name:
          type: string
        purpose:
          type: string
        rule:
          enum:
            - all
            - pick
          type: string
        count:
          type: integer
        min:
          type: integer
        max:
          type: integer
        from:
          type: string
        from_nested:
          items:
            $ref: '#/components/schemas/SubmissionRequirement'
          type: array
      required:
        - rule
      type: object
    InputDescriptor:
      additionalProperties: false
      properties:
        id:
          type: string
        constraints:
          $ref: '#/components/schemas/Constraints'
        name:
          type: string
        purpose:
          type: string
        format:
          $ref: '#/components/schemas/Format'
        group:
          items:
            type: string
          type: array
      required:
        - constraints
        - id
      type: object
    Constraints:
      additionalProperties: false
      properties:
        limit_disclosure:
          enum:
            - required
            - preferred
          type: string
        statuses:
          $ref: '#/components/schemas/Constraints_statuses'
        fields:
          items:
            $ref: '#/components/schemas/Field'
          type: array
        subject_is_issuer:
          enum:
            - required
            - preferred
          type: string
        is_holder:
          items:
            $ref: '#/components/schemas/HolderSubject'
          type: array
        same_subject:
          items:
            $ref: '#/components/schemas/HolderSubject'
          type: array
      type: object
    PdStatus:
      additionalProperties: false
      properties:
        directive:
          enum:
            - required
            - allowed
            - disallowed
          type: string
      type: object
    HolderSubject:
      additionalProperties: false
      properties:
        field_id:
          items:
            type: string
          type: array
        directive:
          enum:
            - required
            - preferred
          type: string
      required:
        - directive
        - field_id
      type: object
    Field:
      additionalProperties: false
      properties:
        id:
          type: string
        path:
          items:
            type: string
          type: array
        purpose:
          type: string
        filter:
          $ref: '#/components/schemas/Filter'
        predicate:
          enum:
            - required
            - preferred
          type: string
      type: object
    Filter:
      additionalProperties: false
      properties:
        _const:
          $ref: '#/components/schemas/Filter__const'
        _enum:
          items:
            $ref: '#/components/schemas/Filter__const'
          type: array
        exclusiveMinimum:
          $ref: '#/components/schemas/Filter__const'
        exclusiveMaximum:
          $ref: '#/components/schemas/Filter__const'
        format:
          type: string
        formatMaximum:
          type: string
        formatMinimum:
          type: string
        formatExclusiveMaximum:
          type: string
        formatExclusiveMinimum:
          type: string
        minLength:
          type: integer
        maxLength:
          type: integer
        minimum:
          $ref: '#/components/schemas/Filter__const'
        maximum:
          $ref: '#/components/schemas/Filter__const'
        not:
          type: object
        pattern:
          type: string
        contains:
          $ref: '#/components/schemas/Filter'
        items:
          $ref: '#/components/schemas/Filter_items'
        type:
          type: string
      type: object
    NotFoundError:
      additionalProperties: false
      example:
        traceId: traceId
        name: NotFoundError
        details:
          - issue: issue
            field: field
            location: location
            value: value
          - issue: issue
            field: field
            location: location
            value: value
        message: 'Not found: ${param}.'
        httpStatusCode: 6
      properties:
        name:
          enum:
            - NotFoundError
          type: string
        message:
          enum:
            - 'Not found: ${param}.'
          type: string
        httpStatusCode:
          enum:
            - 404
          type: integer
        traceId:
          type: string
        details:
          items:
            $ref: '#/components/schemas/NotFoundError_details_inner'
          type: array
      required:
        - httpStatusCode
        - message
        - name
        - traceId
      type: object
    InvalidParameterError:
      additionalProperties: false
      example:
        traceId: traceId
        name: InvalidParameterError
        details:
          - issue: issue
            field: field
            location: location
            value: value
          - issue: issue
            field: field
            location: location
            value: value
        message: 'Invalid parameter: ${param}.'
        httpStatusCode: 0
      properties:
        name:
          enum:
            - InvalidParameterError
          type: string
        message:
          enum:
            - 'Invalid parameter: ${param}.'
          type: string
        httpStatusCode:
          enum:
            - 400
          type: integer
        traceId:
          type: string
        details:
          items:
            $ref: '#/components/schemas/NotFoundError_details_inner'
          type: array
      required:
        - httpStatusCode
        - message
        - name
        - traceId
      type: object
    CredentialRequirements_constraints:
      anyOf:
        - items:
            type: string
          type: array
        - items:
            additionalProperties:
              items: {}
              type: array
            properties: {}
            type: object
          type: array
      description: Constraint list of the VC requirements
    Constraints_statuses:
      properties:
        active:
          $ref: '#/components/schemas/PdStatus'
        suspended:
          $ref: '#/components/schemas/PdStatus'
        revoked:
          $ref: '#/components/schemas/PdStatus'
      type: object
    Filter__const:
      oneOf:
        - type: number
        - type: string
    Filter_items:
      oneOf:
        - $ref: '#/components/schemas/Filter'
        - items:
            $ref: '#/components/schemas/Filter'
          type: array
    NotFoundError_details_inner:
      additionalProperties: false
      example:
        issue: issue
        field: field
        location: location
        value: value
      properties:
        issue:
          type: string
        field:
          type: string
        value:
          type: string
        location:
          type: string
      required:
        - issue
      type: object
  securitySchemes:
    UserTokenAuth:
      in: header
      name: authorization
      type: apiKey
    ProjectTokenAuth:
      in: header
      name: authorization
      type: apiKey
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: request
        authorizerUri: arn:aws:apigateway:ap-southeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-1:792104784284:function:iam-dev-ProjectTokenAuthorizerC83BEF45-elvJgVdbp078:live-alias/invocations
        authorizerResultTtlInSeconds: 0
x-amazon-apigateway-request-validators:
  basic:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: basic
